services:
  nginx:
    image: nginx:1.23.1
    volumes:
      - ./backend:/var/www/backend
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - backend
    container_name: symfony_nginx

  backend:
    build:
      context: .
      dockerfile: _docker/Dockerfile
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - database
    container_name: symfony_app

  database:
    image: postgres:17.0
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    container_name: db_postgres

  rabbitMQ:
    image: rabbitmq:4.0.4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    container_name: mailhog

volumes:
  pgdata:
  rabbitmq_data:
