# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    messenger:
        default_bus: messenger.bus.default

        buses:
            messenger.bus.default:
                middleware:
                    - validation
                    - doctrine_transaction

        routing:
            'App\Message\TaskNotificationMessage': async

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: 'delayed'
                        type: topic
                    queues:
                        delayed_messages:
                            arguments:
                                x-delayed-type: 'direct'
                serializer: messenger.transport.symfony_serializer

    scheduler:
        enabled: true

    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
